apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loteria-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: 'https://github.com/sueliopontes/loteria-infra-deploy' # substitua aqui
    targetRevision: HEAD
    path: k8s/dev

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
