apiVersion: apps/v1
kind: Deployment
metadata:
  name: loteria
  labels:
    app: loteria-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loteria
  template:
    metadata:
      labels:
        app: loteria
    spec:
      containers:
        - name: loteria
          image: sueliopontes/loteria@sha256:333a21f5f5de96518bef036dfdc01f3c0c83f6ae9cbf1ae75007bfff06f3b848
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__MongoDb
              value: mongodb://admin:senha123@mongo:27017
---
apiVersion: v1
kind: Service
metadata:
  name: loteria-service
spec:
  type: ClusterIP
  selector:
    app: loteria
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80